# Generated by Django 4.0.5 on 2022-08-15 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='home',
        ),
    ]
